language: java
sudo: required
env:
  - TRAVIS_NODE_VERSION="6"
  
before_install:
  - nvm install node
  
before_script:
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- sudo apt-get install nodejs
- sudo apt-get install build-essential

script: mvn clean package
after_success:
  - bash <(curl -s https://codecov.io/bash)
